### ISSUE TITLE
Mess up articles on www.economist.com

### ISSUE THREAD

**Issue by woaidangyang** [Strajk/words-unknown#2]
Hi,

Thanks for this useful extension. Could you please help have look at this issue? When I enable this extension, the contents of the articles on www.economist.com are messed up.

Thanks!

**Comment by Strajk** [comment]
Hey @woaidangyang , thx for reminding me I've made this extension – I totally forgot about it, but now I'll start using it again cause I still find it useful :D 

I just tried it, and it seems to work fine... what issues do u have?

https://user-images.githubusercontent.com/697301/185164654-20b3bb35-f8b2-43dc-ad91-d80ae8e52eb5.mp4

**Comment by woaidangyang** [comment]
Hi Strajk, thank you so much for your extension.

I reinstalled the extension again today and found it works normally now! I'll keep you updated if the issue comes again.
